### ISSUE TITLE
Won't work with RBR850

### ISSUE THREAD

**Issue by mrj1m0thy** [bkerler/netgear_telnet#12]
Not sure if its because the new firmware version doesn't allow this. But the script runs without issue but still can't telnet in :'( 
Hardware Version:        RBR850
Firmware Version:         V4.6.3.16_2.0.51
GUI Language Version: V3.0.1.2_2.1.30.3

If there's any information I can provide to make this work with this router I'd love to help. Can code python but I'm very unfamilar with the way the requests interface with the router. Didn't dig into that rabbit hole. But willing to dive in if no one else will. 

Just want to separate my SSID for 2,4 and 5 so that I can connect my "Landroid WR155" to the wifi -_- my galaxy s8 will ONLY connect to 5ghz even if i "disable" 5ghz in the web interface.. So dumb and frustrating. Anywho, let me know if i can help

**Comment by bkerler** [comment]
@mrj1m0thy Please try commit 57ca519e2571473589327aa15bd3e44b0159b49e

**Comment by lt201081** [comment]
可以实现的 只不过比较麻烦而已！

**Comment by lt201081** [comment]
What can be achieved is just more trouble!
