### ISSUE TITLE
Script fails to operate if password contains ampersand 

### ISSUE THREAD

**Issue by loaderladdy** [bkerler/netgear_telnet#15]
Example - ./telnet-enable2.py 192.168.1.1 A0:40:A0:69:B6:30 admin “yourpass”

If “yourpass” contains an “&” then python cannot correctly parse the attributes and throws an error, I.e., for instance, if the password was 12345&67890 then bash would output the following

` -bash: 67890: command not found`

**Comment by rlueder** [comment]
Just wrap your password with double quotes so it's treated as a string and that should do it (my pwd had a parenthesis and that solved it for me).

**Comment by bkerler** [comment]
Will add that to the readme, thanks for the hint ;)
