### ISSUE TITLE
VirusTotal 

### ISSUE THREAD

**Issue by CozyKeybord** [bkerler/netgear_telnet#16]
![Screenshot 2022-07-12 143301](https://user-images.githubusercontent.com/107009893/178568649-01389a2c-a142-465f-aec7-6bb2c4224cf5.png)

?

**Comment by rlueder** [comment]
From [README](https://github.com/bkerler/netgear_telnet/tree/main/pyinstaller_native_bins) under `/pyinstaller_native_bins`:

> This folder contains pyinstaller compiled binaries for Debian 10 (Buster) and Windows 10 (1909). The following AntiVirus software falsely identifies the Windows binary as a trojan/malware:

> So you'll need to set an exclusion in those AVs in order to use it unmolested under Windows. Otherwise, just install Python for windows and run the script natively.
