### ISSUE TITLE
Works with Netgear Nighthawk AX12 / RAX120v2

### ISSUE THREAD

**Issue by boretom** [bkerler/netgear_telnet#18]
Just wanted to let you know that this script works with my Nighthawk AX12 / RAX120v2, run from Linux Mint 21.
I was successful (only) with the precompiled script in the `pyinstaller_native_bins`.

Thanks a lot for your work!

**Comment by bkerler** [comment]
Great, can you also let me know the firmware version ?

**Comment by boretom** [comment]
Sure, forgot to specify it: it's version  V1.2.8.40

**Comment by bkerler** [comment]
Thanks :)

**Comment by boretom** [comment]
Just a little addition ... The AX12 is not of the Orbi family but Nighthawk ([link to product page](https://www.netgear.com/de/home/wifi/routers/rax120/)) :)

**Comment by ShiawasenaHoshi** [comment]
Confirmed working on Nighthawk AX12 / RAX120v2 **V1.2.9.52** (Kubuntu 20.04)
