### ISSUE TITLE
Orbi RBK40 issue

### ISSUE THREAD

**Issue by uSlackr** [bkerler/netgear_telnet#2]
Running the command on RBK40 router produces: 
`print(f"Can't connect to {ip}:{port}")
                                                      ^` 
with the caret beneath the double quote.  I have a couple questions on the command format.  I'm using the MAC address with all CAPS and ":" as a separator.   Is there a spec on the format?  Also, How do I know which is the br0 interface?  I'm using the LAN MAC from the admin interface.  
I'd be glad to up date docs and issue a PR once we define it better.  
Thanks

**Comment by bkerler** [comment]
Mac format as it is, : do not matter. The ip should match of course to get a connection.

**Comment by uSlackr** [comment]
Thanks and my apologies - that was a completely bad question.  Here's the better one.  I get a syntax error when I run this:
```
  File "telnet-enable2.py", line 463
    print(f"Can't connect to {ip}:{port}")
                                                        ^
SyntaxError: invalid syntax
```
The caret is pointing to the closed double quotes.  Syntax looks fine to me but I am 
a python n00b.

**Comment by bkerler** [comment]
Most likely you're running the script with outdated python 2.x or python 3 <3.7. Run using python 3.7 or above ;)

**Comment by uSlackr** [comment]
You are correct, sir.  Was running v2.7.  Using this worked:

sudo python3 ./telnet-enable2.py 192.168.1.1 A0:40:A0:63:A6:20 admin <mypassword>

A n00b like I said!

Thank you

\\Greg
________________________________
