### ISSUE TITLE
Confirmed working on RBRE960 v6.3.7.5

### ISSUE THREAD

**Issue by jabronimus** [bkerler/netgear_telnet#20]
Was able to use this to get in, install entware / opkg, and then install dropbear and lots of other packages. Created a new user, can use the new user to SSH into the router!  Setup a crontab so that the dropbear restarts on reboot. Great work!

(Hilariously, i posted this on the netgear forums and my posts were removed very quickly ... lol)

**Comment by bkerler** [comment]
Thanks :)
