### ISSUE TITLE
After running, the following prompt appears, how to solve it?

### ISSUE THREAD

**Issue by lt201081** [bkerler/netgear_telnet#23]
This error occurs when running under windows

![image](https://user-images.githubusercontent.com/31964103/220828088-88e1cdfd-8b5f-4e81-8a94-02d44bf26806.png)

**Comment by W1lli0m** [comment]
there are parameters required to put after telnet-enable2.py, complete syntax is ./telnet-enable2.py 192.168.1.1 [mac address of RBR] admin "admin password"

**Comment by lt201081** [comment]
![image](https://user-images.githubusercontent.com/31964103/220830994-1b9a769a-b502-47d9-ba5e-302c1cec6ab2.png)
no feedback

**Comment by lt201081** [comment]
Please forgive my operational ability! don't know where to start

**Comment by lt201081** [comment]
![image](https://user-images.githubusercontent.com/31964103/220832655-e1abaf7e-6c5e-4d8a-bc22-d1d22d41d6db.png)
Prompt syntax error, but I can't find the problem

**Comment by W1lli0m** [comment]
for your example, you should execute following commands from Windows command prompt

python telnet-enable2.py 192.168.1.1 28:80:88:3E:25:46 admin "admin@ADMIN"

**Comment by lt201081** [comment]
![image](https://user-images.githubusercontent.com/31964103/220835830-1a627d08-4ba5-43ac-b327-9259bc5714ab.png)

**Comment by W1lli0m** [comment]
can you try to upgrade python ver 3.8.x greatest version of 3.8 series? Seems you are still on Windows XP which can only adapt python 3.8.x

**Comment by W1lli0m** [comment]
tried with python v3.8.10 and it works for me
![image](https://user-images.githubusercontent.com/44217741/220843957-32038200-293a-4407-8a9d-88cb0917f928.png)

**Comment by lt201081** [comment]
![image](https://user-images.githubusercontent.com/31964103/220856813-ebffec5b-a543-49b2-b702-cff9ebef258e.png)

**Comment by W1lli0m** [comment]
you need to execute the command from Windows command prompt as this one -

python telnet-enable2.py 192.168.1.1 28:80:88:3E:25:46 admin "admin@ADMIN"

not from python shell

**Comment by lt201081** [comment]
Yes, I entered in windows and then executed the command, the result feedback is like this!
![image](https://user-images.githubusercontent.com/31964103/220859289-844009f4-9c37-4935-a59d-e735f34a0de2.png)

**Comment by W1lli0m** [comment]
you are entering python shell before executing telnet-enable2.py, this is causing the problem

**Comment by lt201081** [comment]
I will try again

**Comment by lt201081** [comment]
Mine is RBR750, is it not suitable for use?

**Comment by Edelwiess** [comment]
@lt201081 try the mac address in Router Information instead of Router Information
I used to have the similar issue of yours, after using the mac address on the Router Information it Finally worked.
![image](https://github.com/bkerler/netgear_telnet/assets/20700559/f7b2b6ea-929b-4d3d-97b5-8c313275c161)
