### ISSUE TITLE
Can't open ./telnet-enable2.py

### ISSUE THREAD

**Issue by Frog-00** [bkerler/netgear_telnet#37]
<img width="716" alt="100747" src="https://github.com/bkerler/netgear_telnet/assets/148702023/6e946251-f190-4c80-ad0d-fc4c76f1b76e">

Does anyone know how to solve this problem?

**Comment by gpz1100** [comment]
Try "\" . 

You're not in linux in windows.

**Comment by Frog-00** [comment]
Thank you.I have modified the code and it can now run, but I can only get blank output. I checked the account,password and MAC address(from"Router Information"), and they are all correct. Why is this?
`python telnet-enable.py 10.0.0.1 3x:9x:Bx:4x:9x:1x admin "Password!!"`
`python telnet-enable.py 10.0.0.1 3x:9x:Bx:4x:9x:1x admin 'Password!!'`
`python .\telnet-enable.py 10.0.0.1 3x:9x:Bx:4x:9x:1x admin 'Password!!'`
`python .\telnet-enable.py 10.0.0.1 3x:9x:Bx:4x:9x:1x admin "Password!!"`
I tried the above formats, but all got blank output.My router is RAX50,Firmware Version is V1.0.12.120_2.0.83

**Comment by gpz1100** [comment]
Try python3 {rest of command line}.

Sorry can't help further.  When I did testing, it will in an ubuntu vm (under windows based vmworkstation 15).

**Comment by grotiusc** [comment]
Having the same issue on RBR750:
```
C:\Temp\netgear>python3 .\telnet-enable.py 192.168.1.1 6x:Cx:Dx:2x:5x:2x admin 'abc1234!'
Netgear Telnet enabler V3.1 (c) B.Kerler 2021-2023

C:\Temp\netgear>telnet 192.168.1.1
Connecting To 192.168.1.1...Could not open connection to the host, on port 23: Connect failed
```
RBR750 - Firmware V4.6.14.3_2.3.12

**Comment by grotiusc** [comment]
Solved by removing the single quotes from the password:

`python3 .\telnet-enable.py 192.168.1.1 6x:Cx:Dx:2x:5x:2x admin abc1234!`

**Comment by therealmrsymba** [comment]
Using RBR750 - Firmware version - V3.2.16.22_1.4.9

can’t seem to get this working and not sure what I am doing wrong.


![Screenshot 2023-10-28 000854](https://github.com/bkerler/netgear_telnet/assets/64728541/7c79cb1b-c321-4243-8f7c-3b443c555514)
