### ISSUE TITLE
Confirmed working on RAX70 with Firmware Version 1.0.10.110

### ISSUE THREAD

**Issue by Iliasbrv** [bkerler/netgear_telnet#43]
Thank you very much for your amazing work!
I managed to enable telnet on my RAX70 in order to change Region (it was locked to China and I live in Europe and I really needed that 4804MHz option).

I was trying on the oldest Firmware Version 1.0.1.68 with no luck, but trying with 1.0.10.110 it worked.
I got the following Syntax Errors with latest version of Python on Win11:
\telnet-enable.py:50: SyntaxWarning: invalid escape sequence '\s'
  for v in (re.split('\s+', i) for i in arp_data_raw))
\telnet-enable.py:660: SyntaxWarning: invalid escape sequence '\s'
  for line in re.findall('([-.0-9]+)\s+([-0-9a-f]{17})\s+(\w+)', data):

and then the message **Done sending pw data XXXXXXXXXX to 192.168.1.1:23**

But finally everything worked as a charm and I connected to Telnet!

I have to notice here that I was trying using single quotes on 'password' and no quotes on password on my unsuccessful tries.
I was getting the same Syntax Errors and then the message:
Done sending pw data XXXXXXXXXX to 192.168.1.1:23 but after rebooting I could not connect to telnet.

With fw 1.0.10.110 it was the first time I tried with double quotes on "password". I cannot tell if it was the quotes or the firmware version that allowed to enable telnet.

PS: running telnet-enable.py from Ubuntu 22.04 returned no Syntax Errors at all.

**Comment by ttonyyao** [comment]
Thank you for sharing @Iliasbrv My issue was i got Done sending pw data xxxxxxxxxxxxxxxxxxxx, to 192.168.1.1:23, but i was not able to telent to my router. This is was quite weird. Do you have any clue?

**Comment by Iliasbrv** [comment]
I was getting the same message with the Firmware Version 1.0.1.68 and the latest Netgear Firmware without being able to telnet the router. I tried Firmware Version 1.0.10.110 and run telnet after Done sending pw data without restarting my router.
Make sure telnet is enabled on Windows features.

**Comment by Iliasbrv** [comment]
Hello @zh-pan 
Yes you can update your Router without any problem.
After updating to the latest FW you have 6 Region Options:
Australia & New Zeland
Europe
Hong Kong
India
Middle East (United Arab Emirates)
Singapore

**Comment by zh-pan** [comment]
@Iliasbrv Thanks again! I try it and success!

**Comment by Iliasbrv** [comment]
Of course. Thanks for the reminder!

**Comment by Iliasbrv** [comment]
Off course. Thanks for the reminder! 🙂
